### ISSUE TITLE
main function erroe

### ISSUE THREAD

**Issue by mohanapriyamanik** [shwoo93/video_decaptioning#7]
while running main im getting following error..pls help me to resolve as soon as possible

run
train at epoch 1
Traceback (most recent call last):
  File "/content/drive/My Drive/video_decaptioning-master/main.py", line 214, in <module>
    train_loss, train_acc = train_epoch(i, train_loader, model, criterion, optimizer, opt, train_logger, train_batch_logger, viz, train_lot,netD, optimizerD, criterion2, netG, optimizerG, criterion3)
  File "/content/drive/My Drive/video_decaptioning-master/train.py", line 60, in train_epoch
    for i, (inputs, targets) in enumerate(Dataloader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/drive/My Drive/video_decaptioning-master/video_decaptioning_data.py", line 177, in __getitem__
    clip = torch.stack(clip, 0).permute(1, 0, 2, 3)
RuntimeError: expected a non-empty list of Tensors

**Comment by srivinodp** [comment]
are you converting to imgs using video.png first ?
